### ISSUE TITLE
Store rotation / skew components in degrees?

### ISSUE THREAD

**Issue by behdad** [googlefonts/variable-components-in-ufo#1]
Currently they look like in radians. Suggest storing in degrees.

**Comment by justvanrossum** [comment]
Should definitely be degrees. Where do you observe radians? The doc here specifies degrees.

**Comment by behdad** [comment]
Sorry. Just adjust the sample code:
```
translate(tCenterX, tCenterY)
translate(translateX, translateY)
rotate(rotation)
scale(scaleX, scaleY)
skew(skewX, skewY)  # transform([1, tan(skewY), tan(-skewX), 1, 0, 0])
translate(-tCenterX, -tCenterY)
```

**Comment by behdad** [comment]
Since I copied that and then had to adjust it.

**Comment by behdad** [comment]
Also the two translates at the beginning can be combined.

**Comment by justvanrossum** [comment]
It labeled as "pseudo code", the actual code converts explicitly:
https://github.com/BlackFoundryCom/variable-components-in-ufo/blob/f611a8557ea873e57f8aca998bfdedb6108f8a88/compose_transform.py#L18-L37

> Also the two translates at the beginning can be combined.

Correct. I left it like this to make the symmetry with the final translate more obvious.
