### ISSUE TITLE
Missing source entries in example designspace?

### ISSUE THREAD

**Issue by rsheeter** [googlefonts/variable-components-in-ufo#15]
I must be missing something obvious, why don't the ExampleVariableComponent_Default.ufo/glyphs.blah directories have a source source referencing them in [ExampleVariableComponent.designspace](https://github.com/googlefonts/variable-components-in-ufo/blob/main/ExampleVariableComponent/ExampleVariableComponent.designspace).

For context, I thought I'd find a source similar to https://github.com/googlefonts/fontc/blob/a426fe03a72a1a10fa0f11900347e2e1f6f96e47/resources/testdata/wght_var.designspace#L17.

**Comment by justvanrossum** [comment]
These are layers used by the "local" designspace, as part of the `com.black-foundry.glyph-designspace` lib key:

https://github.com/googlefonts/variable-components-in-ufo/blob/a135807edd0961765619f1c87044fd3cde416452/ExampleVariableComponent/ExampleVariableComponent_Default.ufo/glyphs/V_ariableG_lyph.glif#L38-L68

**Comment by rsheeter** [comment]
Ah, ty. Working as intended then :)
